# Generated by Django 3.1.3 on 2020-11-26 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LookupValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgboard.lookupcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateField()),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messages_author', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(limit_choices_to={'category_id': 1}, on_delete=django.db.models.deletion.RESTRICT, related_name='messages_board', to='msgboard.lookupvalues')),
                ('labels', models.ManyToManyField(limit_choices_to={'category_id': 2}, related_name='messages_label', to='msgboard.LookupValues')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msgboard.messages')),
                ('tags', models.ManyToManyField(related_name='messages_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], default='U', max_length=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view_date', models.DateField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgboard.messages')),
                ('reaction', models.ForeignKey(blank=True, limit_choices_to={'category_id': 3}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='msgboard.lookupvalues')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='views',
            field=models.ManyToManyField(related_name='messages_views', through='msgboard.MessageViews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='messageviews',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='u_msg_user'),
        ),
    ]
