# Generated by Django 4.0.1 on 2022-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgboard', '0002_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
