apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/ifireball/beyond-tutorial
      revision: openshift-compat
      directories:
      - path: argocd/infra/*
  template:
    metadata:
      name: '{{path.basenameNormalized}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/ifireball/beyond-tutorial
        targetRevision: openshift-compat
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
